version: '3.9'
services:
  frontend:
    build:
        context: ./app/frontend
        dockerfile: Dockerfile
    container_name: frontend-diploma
    ports: 
        - "5000:5000"
        - "8000:8000"
    networks:
        - front-back
    depends_on:
        - backend
    healthcheck:
        test: curl -f http://localhost:5000/ || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s
    restart: "unless-stopped"
  backend:
    build:
        context: ./app/backend
        dockerfile: Dockerfile
    container_name: backend-diploma
    ports:
        - "3000:3000"
    networks:
        - front-back
        - back-database
    depends_on:
        database:
            condition: service_healthy
    healthcheck:
        test: curl -f http://localhost:3000/api/name_tables/ || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s
    restart: "unless-stopped"
  database:
    image: mariadb:latest
    container_name: database-diploma
    volumes:
        - data:/var/lib/mysql/
    ports:
        - "3306:3306"
    networks:
        - back-database
    env_file: .env
    environment:
        - MARIADB_ROOT_PASSWORD=${PASSWORD}
        - MARIADB_USER=${USER}
        - MARIADB_PASSWORD=${PASSWORD}
        - MARIADB_DATABASE=${DB}
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent", "-uroot", "-p${PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 5
    restart: "unless-stopped"
networks:
  front-back:
      driver: bridge
  back-database:
      driver: bridge
volumes:
  data:    