apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.stage }}
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: {{ .Chart.Name }}
             port: 
                number: {{ .Values.service.port }}