apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.stage }}
  labels:
    app   : {{ .Chart.Name }}
    env   : {{ .Values.stage }}   
spec:
  type: ClusterIP
  selector:
    env: {{ .Values.stage }}
    app: {{ .Chart.Name }}   
  ports:
    - protocol  : TCP
      name      : main
      port      : {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.portsContainer }}
    - protocol  : TCP
      name      : metrics
      port      : {{ .Values.service.ports_metrics }}
      targetPort: {{ .Values.deployment.ports_metrics }}
    