apiVersion : v2
name       : helm-whatweather-db
type       : application
description: Epam24 Diploma DB
version    : 1.0.0
appVersion : "1.0.0"


keywords:
  - namespace
  - secret
  - service


maintainers:
  - name : Valentin Kozlov
    email: valentin_kozlov@epam.com