apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.stage }}
  labels:
    app   : {{ .Chart.Name }}
    env   : {{ .Values.stage }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app   : {{ .Chart.Name }}
      env   : {{ .Values.stage }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app   : {{ .Chart.Name }}
        env   : {{ .Values.stage }}
    spec:
      containers:
      - name : {{ .Chart.Name }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.deployment.portsContainer }}
        - containerPort: {{ .Values.deployment.ports_metrics}}
        resources:
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
        envFrom:
          - secretRef:
              name: db-dev