stage: dev

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 20

deployment:
  image: 280720853053.dkr.ecr.eu-central-1.amazonaws.com/whatweather-front:v1
  portsContainer: 5000
  resources:
    limits:
      cpu: "200m"
      memory: "200Mi"
    requests:
      cpu: "100m"
      memory: "100Mi"

service:
  port: 5000