apiVersion: v1
kind: Secret
metadata:
  name: db-dev
  namespace: {{ .Values.stage }}
type: Opaque
data:
  username_db: {{ .Values.secret.user }}
  password_db: {{ .Values.secret.pass }}
  database: {{ .Values.secret.db }}
  name_service_db: {{ .Values.secret.name_service_db }}