  apiVersion: v1
  kind: Secret
  metadata:
    name: db-dev
    namespace: dev
  type: Opaque
  data:
    username_db: {{ .Values.secret.user }}
    password_db: {{ .Values.secret.pass }}
    database: {{ .Values.secret.db }}
    name_service_db: {{ .Chart.Name }}