apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.stage }}
  labels:
    app   : {{ .Chart.Name }}
    env   : {{ .Values.stage }}
spec:
  externalName: {{ .Values.service.externalName }}
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  sessionAffinity: None
  type: ExternalName